name: o3_cards
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  local_auth: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
      - assets/splash.gif
