name: o3_cards
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  api_cache_manager: ^1.0.2
  auto_size_text: ^3.0.0
  carousel_slider: ^4.1.1
  circular_profile_avatar: ^2.0.5
  convex_bottom_bar: ^3.0.0
  custom_pin_screen: ^0.3.0
  dots_indicator: ^2.1.0
  dotted_border: ^2.0.0+3
  email_validator: ^2.0.1
  firebase_core:
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_lints: ^1.0.0
  flutter_platform_alert: ^0.3.0
  flutter_pw_validator: ^1.4.2
  flutter_spinkit: ^5.1.0
  flutter_toggle_tab: ^1.2.0
  flutterbudpay: ^0.0.2
  font_awesome_flutter: ^10.1.0
  get:
  google_fonts: ^3.0.1
  hexcolor: ^2.0.7
  http: ^0.13.4
  icons_launcher: ^1.1.8
  iconsax: ^0.0.8
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  keyboard_actions: ^4.0.1
  local_auth: ^2.1.0
  local_session_timeout: ^2.1.2
  mono_flutter: ^1.1.3
  nigerian_states_and_lga: ^1.0.0
  page_view_indicators: ^2.0.0
  progress_indicators: ^1.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences:
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  snippet_coder_utils: ^1.0.12
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: 'assets/o3-logo.jpeg'
  ios: true
  android: true
flutter:
  uses-material-design: true
  assets:
      - .env
      - assets/splash.gif
      - assets/onboardimg.png
      - assets/onboardimg2.png
      - assets/CapitalLogoSoloIcon_ImageView_7-1596x1824.png
      - assets/card_prestige.png
      - assets/card_classic.png
      - assets/classic_card.jpg
      - assets/card_prestige_ptr.png
      - assets/cardimgplatinum_ptr.png
      - assets/cardimgprepaid_ptr.png
      - assets/classic_card_Ptr.jpg
      - assets/CapitalLogoIcon_ImageView_46-190x110.png
      - assets/1vrfyidentity.png
      - assets/onboardbgrd.png
      - assets/buyairtimeanddata.png
      - assets/paybillsandfees.png
      - assets/cardplaceholder.png
      - assets/cardplaceholder2.png
      - assets/loadinganimation.gif
      - assets/loadinganimation2.gif
      - assets/loadinganimation3.gif
      - assets/loadinganimation4.gif
      - assets/03CapitalLogoSoloIcon1.png
      - assets/vervelogo.png
      - assets/amexlogo.png
      - assets/person.png
      - assets/cardimgprepaid.png
      - assets/cardimgplatinum.png
      - assets/cardimgbusinesscredit.png
      - assets/send_icon.png
      - assets/send_icon_white.png
      - assets/face-id.png
      - assets/topcurve.png
      - assets/bottomcurve.png
      - assets/ca/lets-encrypt-r3.pem

