name: o3_cards
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  api_cache_manager: ^1.0.2
  auto_size_text: ^3.0.0
  carousel_slider: ^4.1.1
  convex_bottom_bar: ^3.0.0
  dots_indicator: ^2.1.0
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  icons_launcher: ^1.1.8
  iconsax: ^0.0.8
  intl: ^0.17.0
  local_auth: ^2.1.0
  progress_indicators: ^1.0.0
  pull_to_refresh: ^2.0.0
  snippet_coder_utils: ^1.0.12
  toggle_switch: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: 'assets/o3-logo.jpeg'
  ios: true
  android: true
flutter:
  uses-material-design: true
  assets:
      - assets/splash.gif
      - assets/onboardimg.png
      - assets/onboardimg2.png
      - assets/CapitalLogoSoloIcon_ImageView_7-1596x1824.png
      - assets/card_prestige.png
      - assets/card_classic.png
      - assets/CapitalLogoIcon_ImageView_46-190x110.png
      - assets/1vrfyidentity.png
      - assets/onboardbgrd.png
      - assets/buyairtimeanddata.png
      - assets/paybillsandfees.png
      - assets/cardplaceholder.png
      - assets/cardplaceholder2.png
      - assets/loadinganimation.gif
      - assets/loadinganimation2.gif
      - assets/loadinganimation3.gif
      - assets/loadinganimation4.gif
      - 03CapitalLogoSoloIcon1.png

