// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtC03NI_pS68CWuWi-JWSZjZdvEHJVmk',
    appId: '1:985888370081:web:54f02d3144dce92d77afe0',
    messagingSenderId: '985888370081',
    projectId: 'o3cards-17a2c',
    authDomain: 'o3cards-17a2c.firebaseapp.com',
    storageBucket: 'o3cards-17a2c.appspot.com',
    measurementId: 'G-PBT0RX2XCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-X-izAas2CyhwB295HwU3UHBEbL_350',
    appId: '1:985888370081:android:e9e1c8cbe9ca059c77afe0',
    messagingSenderId: '985888370081',
    projectId: 'o3cards-17a2c',
    storageBucket: 'o3cards-17a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsb0IEKdbr4ATRSBSvaG0SvuF_ya6CScM',
    appId: '1:985888370081:ios:4f73f80fc3ef439777afe0',
    messagingSenderId: '985888370081',
    projectId: 'o3cards-17a2c',
    storageBucket: 'o3cards-17a2c.appspot.com',
    iosClientId: '985888370081-l8ae59htmfajc8llbcnemdk9m1rc0duh.apps.googleusercontent.com',
    iosBundleId: 'com.o3capital.o3cards',
  );
}
